CREATE TABLE `will_instructions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`referenceNumber` varchar(32) NOT NULL,
	`appointmentDate` varchar(32),
	`appointmentTime` varchar(16),
	`consultantName` varchar(128),
	`consultantEmail` varchar(320),
	`consultantPhone` varchar(32),
	`caseCoordinatorName` varchar(128),
	`caseCoordinatorEmail` varchar(320),
	`caseCoordinatorPhone` varchar(32),
	`priceQuoted` varchar(32),
	`estimatedDraftDate` varchar(32),
	`productsOrdered` json,
	`willType` varchar(32),
	`lpaType` varchar(64),
	`client1Prefix` varchar(16),
	`client1FirstName` varchar(128),
	`client1MiddleName` varchar(128),
	`client1LastName` varchar(128),
	`client1Dob` varchar(16),
	`client1AddressLine1` varchar(256),
	`client1City` varchar(128),
	`client1Postcode` varchar(16),
	`client1MaritalStatus` varchar(32),
	`client1JobTitle` varchar(128),
	`client1DaytimePhone` varchar(32),
	`client1Mobile` varchar(32),
	`client1Email` varchar(320),
	`client1Nationality` varchar(64),
	`client2Prefix` varchar(16),
	`client2FirstName` varchar(128),
	`client2MiddleName` varchar(128),
	`client2LastName` varchar(128),
	`client2Dob` varchar(16),
	`client2AddressLine1` varchar(256),
	`client2City` varchar(128),
	`client2Postcode` varchar(16),
	`client2MaritalStatus` varchar(32),
	`client2JobTitle` varchar(128),
	`client2DaytimePhone` varchar(32),
	`client2Mobile` varchar(32),
	`client2Email` varchar(320),
	`client2Nationality` varchar(64),
	`executors` json,
	`trustees` json,
	`guardians` json,
	`beneficiaries` json,
	`childrenBenefitAge` varchar(8),
	`disasterClauseClient1` text,
	`disasterClauseClient2` text,
	`propertyOwned` varchar(8),
	`propertyAddress` text,
	`propertyOwnership` varchar(32),
	`mortgageOutstanding` varchar(8),
	`propertyValue` varchar(32),
	`hasOtherProperties` varchar(8),
	`otherProperties` text,
	`bankAccounts` text,
	`investments` text,
	`pensionDetails` text,
	`lifeInsurance` text,
	`businessInterests` text,
	`estimatedEstateValue` varchar(32),
	`specificGifts` json,
	`residuaryEstate` text,
	`residuaryBackup` text,
	`funeralType` varchar(32),
	`funeralWishes` text,
	`organDonation` varchar(8),
	`hasVulnerableBeneficiary` varchar(8),
	`vulnerableBeneficiaryDetails` text,
	`careConcerns` varchar(8),
	`careConcernDetails` text,
	`specialNotes` text,
	`recommendationsJson` json,
	`aiRecommendationNarrative` text,
	`aiClientEmailDraft` text,
	`status` enum('draft','submitted','processing','complete') NOT NULL DEFAULT 'submitted',
	`emailSent` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `will_instructions_id` PRIMARY KEY(`id`),
	CONSTRAINT `will_instructions_referenceNumber_unique` UNIQUE(`referenceNumber`)
);
