/**
 * willDocxConverter.ts
 *
 * Produces a professional Last Will & Testament Word document (.docx) from a FullMatter,
 * matching the layout and content of the PDF generated by willV2Generator.
 *
 * Uses the `docx` package (bundled into api/index.mjs) — no runtime dependency on html-to-docx.
 *
 * Two exports:
 *   generateWillDocxFromMatter(matter, testatorRole) → Buffer  (primary, data-driven)
 *   htmlToDocx(html, title)                           → Buffer  (fallback for edited HTML)
 */
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  AlignmentType,
  ImageRun,
  PageBreak,
  BorderStyle,
  UnderlineType,
  convertInchesToTwip,
} from "docx";
import { readFileSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import type { FullMatter } from "./mattersDb";
import type { MatterClient, MatterExecutor, MatterGuardian, MatterBeneficiary } from "../drizzle/schema";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ── Constants ─────────────────────────────────────────────────────────────────
const FONT = "Times New Roman";
const BODY_SIZE = 22;            // 11pt in half-points
const H2_SIZE = 26;              // 13pt
const H3_SIZE = 23;              // 11.5pt
const COVER_TITLE_SIZE = 44;     // 22pt
const COVER_NAME_SIZE = 36;      // 18pt
const COVER_SMALL_SIZE = 20;     // 10pt

// ── Logo loader ───────────────────────────────────────────────────────────────
function loadLogo(): Buffer | null {
  const candidates = [
    join(__dirname, "genesis-logo.png"),
    join(__dirname, "../server/genesis-logo.png"),
    join(process.cwd(), "server/genesis-logo.png"),
  ];
  for (const p of candidates) {
    if (existsSync(p)) return readFileSync(p);
  }
  return null;
}

// ── Date helpers ──────────────────────────────────────────────────────────────
function formatDate(iso?: string | null): string {
  if (!iso) return "_______________";
  const d = new Date(iso);
  if (isNaN(d.getTime())) return iso;
  return d.toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
}
function ordinal(n: number): string {
  const s = ["th", "st", "nd", "rd"];
  const v = n % 100;
  return n + (s[(v - 20) % 10] || s[v] || s[0]);
}
function todayStr(): string {
  const d = new Date();
  return `the ${ordinal(d.getDate())} day of ${d.toLocaleDateString("en-GB", { month: "long" })} ${d.getFullYear()}`;
}
function nameAndAddr(p: { title?: string | null; fullName?: string | null; address?: string | null }): string {
  const displayName = [p.title, p.fullName].filter(Boolean).join(" ") || "_______________";
  return p.address ? `${displayName}, ${p.address}` : displayName;
}

// ── Paragraph factories ───────────────────────────────────────────────────────

function blank(n = 1): Paragraph[] {
  return Array.from({ length: n }, () =>
    new Paragraph({ children: [new TextRun({ text: "", font: FONT, size: BODY_SIZE })] })
  );
}

function centred(text: string, size = BODY_SIZE, bold = false, spaceBefore = 0, spaceAfter = 0): Paragraph {
  return new Paragraph({
    children: [new TextRun({ text, bold, size, font: FONT })],
    alignment: AlignmentType.CENTER,
    spacing: { before: spaceBefore, after: spaceAfter },
  });
}

/**
 * Parse text with [[B]]...[[/B]] bold markers into TextRun array.
 * Also handles **text** markdown-style bold.
 */
function parseMarkedText(text: string, size: number): TextRun[] {
  const runs: TextRun[] = [];
  const normalised = text.replace(/\*\*(.+?)\*\*/g, "[[B]]$1[[/B]]");
  const parts = normalised.split(/(\[\[B\]\]|\[\[\/B\]\])/);
  let bold = false;
  for (const part of parts) {
    if (part === "[[B]]") { bold = true; continue; }
    if (part === "[[/B]]") { bold = false; continue; }
    if (part) runs.push(new TextRun({ text: part, bold, size, font: FONT }));
  }
  return runs.length ? runs : [new TextRun({ text, size, font: FONT })];
}

/** Justified body paragraph — supports [[B]]...[[/B]] inline bold */
function body(text: string, spaceBefore = 80, spaceAfter = 120): Paragraph {
  return new Paragraph({
    children: parseMarkedText(text, BODY_SIZE),
    alignment: AlignmentType.JUSTIFIED,
    spacing: { before: spaceBefore, after: spaceAfter },
  });
}

/** Clause heading e.g. "1. Revocation" */
function clauseHeading(text: string): Paragraph {
  return new Paragraph({
    children: [new TextRun({ text, bold: true, size: H2_SIZE, font: FONT })],
    spacing: { before: 320, after: 100 },
    keepNext: true,
  });
}

/** Sub-heading */
function subHeading(text: string): Paragraph {
  return new Paragraph({
    children: [new TextRun({ text, bold: true, italics: true, size: BODY_SIZE, font: FONT })],
    spacing: { before: 160, after: 60 },
    keepNext: true,
  });
}

/** Bullet list item */
function bullet(text: string): Paragraph {
  return new Paragraph({
    children: parseMarkedText(text, BODY_SIZE),
    alignment: AlignmentType.JUSTIFIED,
    spacing: { before: 60, after: 60 },
    indent: { left: convertInchesToTwip(0.4), hanging: convertInchesToTwip(0.2) },
    bullet: { level: 0 },
  });
}

/** Horizontal rule */
function hr(): Paragraph {
  return new Paragraph({
    children: [new TextRun({ text: "", font: FONT })],
    border: { bottom: { color: "333333", space: 1, style: BorderStyle.SINGLE, size: 6 } },
    spacing: { before: 200, after: 200 },
  });
}

/** Signature line (underscored blank line + label) */
function sigLine(label: string): Paragraph[] {
  return [
    new Paragraph({
      children: [new TextRun({ text: "", font: FONT, size: BODY_SIZE })],
      border: { bottom: { color: "000000", space: 1, style: BorderStyle.SINGLE, size: 4 } },
      spacing: { before: 400, after: 40 },
    }),
    new Paragraph({
      children: [new TextRun({ text: label, size: BODY_SIZE - 2, font: FONT, italics: true })],
      spacing: { before: 0, after: 200 },
    }),
  ];
}

// ── Clause builders ───────────────────────────────────────────────────────────

function buildExecutorParagraphs(
  primary: MatterExecutor[],
  substitute: MatterExecutor[],
): Paragraph[] {
  const paras: Paragraph[] = [];
  if (primary.length === 0) {
    paras.push(body("I appoint my Executor(s) to administer my Estate."));
  } else if (primary.length === 1) {
    paras.push(body(`I appoint [[B]]${nameAndAddr(primary[0])}[[/B]] to be the Executor of this my Will.`));
  } else {
    const names = primary.map(e => `[[B]]${nameAndAddr(e)}[[/B]]`).join(" and ");
    paras.push(body(`I appoint ${names} to be the Executors of this my Will.`));
  }
  if (substitute.length > 0) {
    const subNames = substitute.map(e => `[[B]]${nameAndAddr(e)}[[/B]]`).join(" and ");
    const plural = substitute.length > 1;
    paras.push(body(`In the event that the above Executor${primary.length > 1 ? "s are" : " is"} unable or unwilling to act, I appoint ${subNames} as substitute Executor${plural ? "s" : ""}.`));
  }
  return paras;
}

function buildGuardianParagraphs(
  primary: MatterGuardian[],
  substitute: MatterGuardian[]
): Paragraph[] {
  const paras: Paragraph[] = [];
  if (primary.length === 0) {
    paras.push(body("In the event that any of my children are under the age of 18 years at the date of my death, I appoint my Executor(s) as Guardian(s) of my minor children."));
  } else if (primary.length === 1) {
    paras.push(body(`In the event that any of my children are under the age of 18 years at the date of my death, I appoint [[B]]${nameAndAddr(primary[0])}[[/B]] to be the Guardian of my minor children.`));
  } else {
    const names = primary.map(g => `[[B]]${nameAndAddr(g)}[[/B]]`).join(" and ");
    paras.push(body(`In the event that any of my children are under the age of 18 years at the date of my death, I appoint ${names} to be the Guardians of my minor children.`));
  }
  if (substitute.length > 0) {
    const subNames = substitute.map(g => `[[B]]${nameAndAddr(g)}[[/B]]`).join(" and ");
    const plural = substitute.length > 1;
    paras.push(body(`In the event that the above Guardian${primary.length > 1 ? "s are" : " is"} unable or unwilling to act, I appoint ${subNames} as substitute Guardian${plural ? "s" : ""}.`));
  }
  return paras;
}

function buildResidueParagraphs(
  primary: MatterBeneficiary[],
  fallback: MatterBeneficiary[],
  partner: MatterClient | null | undefined,
  residueToSpouseFirst: boolean,
  ageCondition: number,
  survivorshipDays: number
): Paragraph[] {
  const paras: Paragraph[] = [];
  function benPronoun(b: MatterBeneficiary) {
    if (b.gender === "male") return { subj: "he", poss: "his" };
    if (b.gender === "female") return { subj: "she", poss: "her" };
    return { subj: "they", poss: "their" };
  }
  if (residueToSpouseFirst && partner?.fullName) {
    paras.push(body(`I give the whole of my Estate to my partner [[B]]${partner.fullName}[[/B]] absolutely, provided they survive me by ${survivorshipDays} days.`));
    paras.push(body(`In the event that [[B]]${partner.fullName}[[/B]] does not survive me by ${survivorshipDays} days, or in the event that the above gift fails for any reason, I direct that the residue of my Estate shall be held on trust and distributed as follows:`));
  }
  if (primary.length === 0) {
    paras.push(body(`I give the whole of my Estate to such of my children as survive me and attain the age of ${ageCondition} years, and if more than one in equal shares.`));
  } else if (primary.length === 1) {
    const b = primary[0];
    const share = b.shareFraction ? ` (${b.shareFraction})` : "";
    const { subj, poss } = benPronoun(b);
    const bName = [b.title, b.fullName].filter(Boolean).join(" ") || "_______________";
    paras.push(body(`I give the whole of my Estate${share} to [[B]]${bName}[[/B]]${b.relationship ? `, my ${b.relationship},` : ""} absolutely, provided ${subj} survive${subj === "they" ? "" : "s"} me by ${survivorshipDays} days.`));
    if (b.includeIssue) {
      paras.push(body(`If [[B]]${bName}[[/B]] does not survive me by ${survivorshipDays} days, ${poss} share shall pass to ${poss} issue in equal shares per stirpes.`));
    }
  } else {
    const shareText = primary.map(b => {
      const share = b.shareFraction ? ` (${b.shareFraction})` : "";
      const bName = [b.title, b.fullName].filter(Boolean).join(" ") || "_______________";
      return `[[B]]${bName}[[/B]]${b.relationship ? `, my ${b.relationship},` : ""}${share}`;
    }).join("; ");
    paras.push(body(`I give the residue of my Estate to the following beneficiaries in the shares set out: ${shareText}; provided each survives me by ${survivorshipDays} days.`));
    if (primary.some(b => b.includeIssue)) {
      paras.push(body(`If any of the above beneficiaries does not survive me by ${survivorshipDays} days, their share shall pass to their issue in equal shares per stirpes.`));
    }
  }
  if (fallback.length > 0) {
    const fallbackText = fallback.map(b => {
      const bName = [b.title, b.fullName].filter(Boolean).join(" ") || "_______________";
      return `[[B]]${bName}[[/B]]${b.relationship ? `, my ${b.relationship}` : ""}`;
    }).join(" and ");
    paras.push(body(`In the event that all of the above gifts fail, I give the residue of my Estate to ${fallbackText} in equal shares absolutely.`));
  } else {
    paras.push(body("In the event that all of the above gifts fail, the residue of my Estate shall pass in accordance with the laws of intestacy applicable in England and Wales."));
  }
  return paras;
}

function buildTrustClauseParagraphs(tc: FullMatter["trustClauses"][number], clauseNum: number): Paragraph[] {
  const paras: Paragraph[] = [];
  const trustees = (tc.trustees as Array<{ name: string; address: string }> | null) || [];
  const lifeTenants = (tc.lifeTenants as Array<{ name: string; address: string }> | null) || [];
  const beneficiaries = (tc.beneficiaries as Array<{ name: string; relationship: string }> | null) || [];
  const trusteeStr = trustees.length
    ? trustees.map(t => `[[B]]${t.name}[[/B]]${t.address ? ` of ${t.address}` : ""}`).join(" and ")
    : "my Executors";
  const bensStr = beneficiaries.length
    ? beneficiaries.map(b => `[[B]]${b.name}[[/B]]${b.relationship ? ` (${b.relationship})` : ""}`).join(" and ")
    : "my beneficiaries";

  switch (tc.trustType) {
    case "PPT": case "ppt": {
      const propertyAddr = tc.propertyAddress || "the property";
      const lifeTenantStr = lifeTenants.length
        ? lifeTenants.map(lt => `[[B]]${lt.name}[[/B]]`).join(" and ")
        : "my surviving spouse/civil partner";
      paras.push(clauseHeading(`${clauseNum}. Protective Property Trust`));
      paras.push(body(`I direct my Trustees to hold my share of [[B]]${propertyAddr}[[/B]] upon trust for ${lifeTenantStr} during their lifetime or until they remarry or cohabit, and thereafter for ${bensStr} absolutely.`));
      paras.push(body(`My Trustees for this trust shall be ${trusteeStr}.`));
      break;
    }
    case "NRB": case "nrb": {
      paras.push(clauseHeading(`${clauseNum}. Nil Rate Band Discretionary Trust`));
      paras.push(body(`I give to my Trustees a sum equal to the nil rate band for inheritance tax purposes at the date of my death (the "NRB Sum") to hold upon the following trusts.`));
      paras.push(body(`My Trustees shall hold the NRB Sum upon discretionary trust for the benefit of ${bensStr}.`));
      paras.push(body(`My Trustees for this trust shall be ${trusteeStr}.`));
      break;
    }
    case "RNRB": case "rnrb": {
      paras.push(clauseHeading(`${clauseNum}. Residence Nil Rate Band Trust`));
      paras.push(body(`I direct that my Trustees shall hold my residential property interest upon trust to ensure that the Residence Nil Rate Band is available and maximised for the benefit of my direct descendants.`));
      paras.push(body(`My Trustees for this trust shall be ${trusteeStr}.`));
      break;
    }
    case "BPR": case "bpr": {
      const bizName = tc.namedBeneficiary || "my business interests";
      const ownershipPct = tc.sharePercentage || "100";
      paras.push(clauseHeading(`${clauseNum}. Business Property Relief Trust`));
      paras.push(body(`I give to my Trustees my interest in [[B]]${bizName}[[/B]] (representing approximately ${ownershipPct}% ownership) to hold upon trust for ${bensStr}, with the intention that Business Property Relief shall apply pursuant to the Inheritance Tax Act 1984.`));
      paras.push(body(`My Trustees for this trust shall be ${trusteeStr}.`));
      break;
    }
    case "Vulnerable": case "vulnerable": {
      const benName = tc.namedBeneficiary || "the vulnerable beneficiary";
      const disability = tc.namedBeneficiaryDisability || "their disability";
      paras.push(clauseHeading(`${clauseNum}. Vulnerable Beneficiary Trust`));
      paras.push(body(`I give my Trustees a share of my Estate to hold upon a Vulnerable Beneficiary Trust for the benefit of [[B]]${benName}[[/B]] who has [[B]]${disability}[[/B]], in accordance with the Taxation of Chargeable Gains Act 1992 and the Finance Act 2005.`));
      paras.push(body(`My Trustees for this trust shall be ${trusteeStr}.`));
      break;
    }
    case "BereavedMinor": case "bereaved_minor": {
      const benName = tc.namedBeneficiary || "my minor children";
      paras.push(clauseHeading(`${clauseNum}. Bereaved Minor Trust`));
      paras.push(body(`I direct my Trustees to hold the share of my Estate for [[B]]${benName}[[/B]] upon a Bereaved Minor Trust pursuant to section 71A of the Inheritance Tax Act 1984, until they attain the age of 18 years.`));
      paras.push(body(`My Trustees for this trust shall be ${trusteeStr}.`));
      break;
    }
    case "18to25": case "age18to25": {
      const benName = tc.namedBeneficiary || "my children";
      const vestAge = tc.ageVesting || 25;
      paras.push(clauseHeading(`${clauseNum}. 18-to-25 Trust`));
      paras.push(body(`I direct my Trustees to hold the share of my Estate for [[B]]${benName}[[/B]] upon an 18-to-25 Trust pursuant to section 71D of the Inheritance Tax Act 1984, until they attain the age of ${vestAge} years.`));
      paras.push(body(`My Trustees for this trust shall be ${trusteeStr}.`));
      break;
    }
    default:
      if (tc.notes) {
        paras.push(clauseHeading(`${clauseNum}. Special Trust Provision`));
        paras.push(body(tc.notes));
      }
  }
  if (tc.notes && tc.trustType !== "default") {
    paras.push(body(tc.notes));
  }
  return paras;
}

function buildAttestationBlock(name: string): Paragraph[] {
  const paras: Paragraph[] = [];
  paras.push(hr());
  paras.push(new Paragraph({
    children: [new TextRun({ text: "The Testimonium and Attestation", bold: true, size: H2_SIZE, font: FONT })],
    spacing: { before: 280, after: 100 },
    keepNext: true,
  }));
  paras.push(body("IN WITNESS whereof I have hereunto set my hand to this my Last Will and Testament on the day and year first above written."));
  paras.push(body(`[[B]]SIGNED[[/B]] by the above-named Testator [[B]]${name}[[/B]] as their Last Will in our joint presence and then by each of us in the presence of the Testator and each other:`));
  paras.push(...sigLine(`Signature of Testator — ${name}`));
  paras.push(...sigLine("Date"));
  paras.push(...blank(1));
  paras.push(new Paragraph({
    children: [new TextRun({ text: "Witnesses", bold: true, size: H3_SIZE, font: FONT })],
    spacing: { before: 200, after: 80 },
  }));
  for (const n of [1, 2]) {
    paras.push(new Paragraph({
      children: [new TextRun({ text: `Witness ${n}`, bold: true, size: BODY_SIZE, font: FONT })],
      spacing: { before: 200, after: 60 },
    }));
    paras.push(...sigLine(`Signature of Witness ${n}`));
    paras.push(...sigLine("Full Name (print)"));
    paras.push(...sigLine("Address"));
    paras.push(...sigLine("Occupation"));
    if (n === 1) paras.push(...blank(1));
  }
  return paras;
}

// ── Main DOCX generator ───────────────────────────────────────────────────────
export async function generateWillDocxFromMatter(
  matter: FullMatter,
  testatorRole: "testator1" | "testator2" = "testator1"
): Promise<Buffer> {
  const client = matter.clients.find(c => c.clientRole === testatorRole);
  const partnerRole = testatorRole === "testator1" ? "testator2" : "testator1";
  const partner = matter.matterType === "mirror" ? matter.clients.find(c => c.clientRole === partnerRole) : null;
  const name = client?.fullName || "_______________";
  const dob = formatDate(client?.dateOfBirth);
  const address = client?.address || "_______________";
  const fileRef = matter.fileReference || "";

  const execRole = matter.matterType === "mirror" ? testatorRole : "shared";
  const primaryExecutors = matter.executors.filter(e => e.clientRole === execRole && e.executorType === "primary");
  const substituteExecutors = matter.executors.filter(e => e.clientRole === execRole && e.executorType === "substitute");
  const primaryGuardians = matter.guardians.filter(g => g.guardianType === "primary");
  const substituteGuardians = matter.guardians.filter(g => g.guardianType === "substitute");
  const benRole = matter.matterType === "mirror" ? testatorRole : "shared";
  const primaryBeneficiaries = matter.beneficiaries.filter(b => b.clientRole === benRole && b.beneficiaryType === "primary");
  const fallbackBeneficiaries = matter.beneficiaries.filter(b => b.clientRole === benRole && b.beneficiaryType === "fallback");
  const wishRole = matter.matterType === "mirror" ? testatorRole : "shared";
  const wishes = matter.wishes.find(w => w.clientRole === wishRole) || matter.wishes[0];
  const ageCondition = wishes?.ageCondition ?? 18;
  const survivorshipDays = wishes?.survivorshipDays ?? 28;
  const organDonation = !!wishes?.organDonation;
  const organDonationText = wishes?.organDonationText || "I wish to donate my organs for medical purposes.";
  const funeralWishes = wishes?.funeralWishes || "";
  const residueToSpouseFirst = matter.matterType === "mirror" && (wishes?.residueToSpouseFirst ?? 1) === 1;
  const hasMinorChildren = (wishes as any)?.hasMinorChildren !== 0;
  const disasterClauseNotes = (wishes as any)?.disasterClauseNotes || "";
  const generalNotes = (wishes as any)?.generalNotes || "";
  const giftRole = matter.matterType === "mirror" ? testatorRole : "shared";
  const specificGifts = (matter.gifts || []).filter(g => g.clientRole === giftRole);
  const pets = matter.pets || [];
  const properties = matter.properties || [];
  const businesses = matter.businesses || [];
  const trustRole = matter.matterType === "mirror" ? testatorRole : "shared";
  const trustClauses = (matter.trustClauses || []).filter(tc => tc.clientRole === trustRole && tc.enabled);
  const exclusions = (matter.exclusions || []).filter((e: any) => e.clientRole === testatorRole && e.fullName?.trim());

  const children: Paragraph[] = [];

  // ── COVER PAGE ──────────────────────────────────────────────────────────
  const logoData = loadLogo();
  if (logoData) {
    children.push(new Paragraph({
      children: [new ImageRun({ data: logoData, transformation: { width: 180, height: 90 }, type: "png" })],
      alignment: AlignmentType.CENTER,
      spacing: { before: 720, after: 720 },
    }));
  } else {
    children.push(...blank(4));
  }
  children.push(centred("The Last Will & Testament", COVER_TITLE_SIZE, true, 480, 120));
  children.push(centred("of", COVER_NAME_SIZE, false, 0, 120));
  children.push(centred(name.toUpperCase(), COVER_NAME_SIZE, true, 0, 240));
  if (fileRef) children.push(centred(`(REFERENCE / ${fileRef})`, COVER_SMALL_SIZE, false, 0, 480));
  children.push(...blank(3));
  children.push(centred("Genesis Wills and Estate Planning Ltd", COVER_SMALL_SIZE + 2, true, 0, 60));
  children.push(centred("The Business Village, Innovation Way, Barnsley, South Yorkshire S75 1JL", COVER_SMALL_SIZE, false, 0, 40));
  children.push(centred("office@genesisestateplanning.info  |  0330 1180937", COVER_SMALL_SIZE, false, 0, 40));
  children.push(centred("https://www.genesisestateplanning.net/", COVER_SMALL_SIZE, false, 0, 0));
  children.push(new Paragraph({ children: [new PageBreak()] }));

  // ── RECITAL ─────────────────────────────────────────────────────────────
  children.push(new Paragraph({
    children: [
      new TextRun({ text: "THIS IS THE LAST WILL AND TESTAMENT", bold: true, size: BODY_SIZE, font: FONT }),
      new TextRun({ text: " of me, ", size: BODY_SIZE, font: FONT }),
      new TextRun({ text: name, bold: true, size: BODY_SIZE, font: FONT }),
      ...(dob !== "_______________" ? [
        new TextRun({ text: ", born on ", size: BODY_SIZE, font: FONT }),
        new TextRun({ text: dob, bold: true, size: BODY_SIZE, font: FONT }),
        new TextRun({ text: ",", size: BODY_SIZE, font: FONT }),
      ] : []),
      new TextRun({ text: " of ", size: BODY_SIZE, font: FONT }),
      new TextRun({ text: address, bold: true, size: BODY_SIZE, font: FONT }),
      new TextRun({ text: ", made this the ", size: BODY_SIZE, font: FONT }),
      new TextRun({ text: "______ day of ________________________ 20______", size: BODY_SIZE, font: FONT, underline: {} }),
      new TextRun({ text: ".", size: BODY_SIZE, font: FONT }),
    ],
    alignment: AlignmentType.JUSTIFIED,
    spacing: { before: 0, after: 200 },
  }));
  children.push(hr());

  // ── CLAUSE 1: Revocation ────────────────────────────────────────────────
  children.push(clauseHeading("1. Revocation"));
  children.push(body("I hereby revoke all former Wills and Testamentary dispositions previously made by me and declare this to be my Last Will and Testament."));

  // ── CLAUSE 2: Executors ─────────────────────────────────────────────────
  children.push(clauseHeading("2. Appointment of Executors"));
  children.push(...buildExecutorParagraphs(primaryExecutors, substituteExecutors));

  // ── CLAUSE 3+: Guardians (if minor children) ────────────────────────────
  let clauseNum = 3;
  if (hasMinorChildren) {
    children.push(clauseHeading(`${clauseNum}. Appointment of Guardians`));
    children.push(...buildGuardianParagraphs(primaryGuardians, substituteGuardians));
    clauseNum++;
  }

  // ── Definition and Administration ───────────────────────────────────────
  children.push(clauseHeading(`${clauseNum}. Definition and Administration of my Estate`));
  children.push(body(`My "Estate" shall mean all property, assets and rights to which I am beneficially entitled at the date of my death, including all property over which I have a general power of appointment or disposition by Will.`));
  children.push(body("My Executors and Trustees shall have the widest powers of management and administration in relation to my Estate as are set out in this Will and as are conferred by law."));
  clauseNum++;

  // ── Property ─────────────────────────────────────────────────────────────
  if (properties.length > 0) {
    children.push(clauseHeading(`${clauseNum}. Property`));
    for (const p of properties) {
      const addr = p.address || "_______________";
      const ownership = p.ownershipType === "joint_tenants" ? "held as joint tenants"
        : p.ownershipType === "tenants_in_common" ? "held as tenants in common"
        : "held in my sole name";
      const mortgage = p.mortgageOutstanding
        ? ` There is an outstanding mortgage with [[B]]${p.mortgageLender || "the mortgage lender"}[[/B]] which my Executors shall discharge from my Estate.`
        : "";
      const notes = p.propertyNotes ? ` ${p.propertyNotes}` : "";
      children.push(body(`The property at [[B]]${addr}[[/B]] is ${ownership}.${mortgage}${notes}`));
    }
    if (properties.some(p => p.ownershipType === "tenants_in_common")) {
      children.push(body("Where any property is held as tenants in common, my share in that property shall form part of my Estate and shall pass in accordance with the terms of this Will."));
    }
    clauseNum++;
  }

  // ── Business Interests ────────────────────────────────────────────────────
  if (businesses.length > 0) {
    children.push(clauseHeading(`${clauseNum}. Business Interests`));
    for (const b of businesses) {
      const bizName = b.businessName ? `[[B]]${b.businessName}[[/B]]` : "my business interest";
      const bizType = b.businessType ? ` (${b.businessType})` : "";
      const share = b.sharePercentage ? `, representing approximately ${b.sharePercentage} of the issued share capital,` : "";
      const notes = b.businessNotes ? ` ${b.businessNotes}` : "";
      children.push(body(`My interest in ${bizName}${bizType}${share} shall form part of my Estate. My Executors shall have full power to deal with, sell, or continue my business interests as they consider appropriate in the best interests of my Estate and beneficiaries.${notes}`));
    }
    children.push(body("For the avoidance of doubt, my Executors shall be entitled to claim Business Property Relief where applicable in accordance with the Inheritance Tax Act 1984."));
    clauseNum++;
  }

  // ── Specific Gifts ────────────────────────────────────────────────────────
  if (specificGifts.length > 0) {
    children.push(clauseHeading(`${clauseNum}. Specific Gifts`));
    for (const g of specificGifts) {
      const recipient = g.recipientName
        ? `[[B]]${g.recipientName}[[/B]]${g.recipientAddress ? ` of ${g.recipientAddress}` : ""}`
        : "_______________";
      const description = g.giftDescription || "_______________";
      if (g.giftType === "monetary") {
        children.push(body(`I give the sum of ${description} to ${recipient} absolutely, provided they survive me.`));
      } else {
        children.push(body(`I give ${description} to ${recipient} absolutely, provided they survive me.`));
      }
    }
    clauseNum++;
  }

  // ── Pets ──────────────────────────────────────────────────────────────────
  if (pets.length > 0) {
    children.push(clauseHeading(`${clauseNum}. Provision for Pets`));
    for (const p of pets) {
      const petDesc = [p.petName, p.petType].filter(Boolean).join(" the ") || "my pet";
      const carer = p.carerName ? `[[B]]${p.carerName}[[/B]]${p.carerAddress ? ` of ${p.carerAddress}` : ""}` : "my Executors";
      const notes = p.careNotes ? ` ${p.careNotes}` : "";
      children.push(body(`I request that ${carer} take care of ${petDesc} and I ask that my Executors make such reasonable financial provision for their care as they see fit.${notes}`));
    }
    clauseNum++;
  }

  // ── Exclusions ────────────────────────────────────────────────────────────
  if (exclusions.length > 0) {
    children.push(clauseHeading(`${clauseNum}. Exclusion of Persons from Benefit`));
    for (const e of exclusions as any[]) {
      const rel = e.relationship ? `, my ${e.relationship},` : "";
      children.push(body(`I have intentionally made no provision in this my Will for [[B]]${e.fullName}[[/B]]${rel} and I do not wish for them to inherit any part of my estate, whether under this Will or on an intestacy. I have reached this decision after careful consideration, and it is my express wish that they receive no benefit from my estate.`));
    }
    clauseNum++;
  }

  // ── Trust Clauses ─────────────────────────────────────────────────────────
  for (const tc of trustClauses) {
    const trustParas = buildTrustClauseParagraphs(tc, clauseNum);
    if (trustParas.length > 0) {
      children.push(...trustParas);
      clauseNum++;
    }
  }

  // ── Distribution of the Residue ───────────────────────────────────────────
  children.push(clauseHeading(`${clauseNum}. Distribution of the Residue`));
  children.push(...buildResidueParagraphs(primaryBeneficiaries, fallbackBeneficiaries, partner, residueToSpouseFirst, ageCondition, survivorshipDays));
  clauseNum++;

  // ── Conditional Gift at Specified Age ────────────────────────────────────
  children.push(clauseHeading(`${clauseNum}. Conditional Gift at Specified Age of ${ageCondition} Years`));
  children.push(body(`Any beneficiary who has not yet attained the age of ${ageCondition} years at the date of my death shall not be entitled to receive their share of my Estate absolutely until they attain that age. Until such time, my Trustees shall hold the share on trust for that beneficiary, with power to apply the income and capital for their maintenance, education and benefit.`));
  children.push(body(`If any beneficiary should die before attaining the age of ${ageCondition} years, their share shall pass as if they had predeceased me.`));
  clauseNum++;

  // ── Executor and Trustee Powers ───────────────────────────────────────────
  children.push(clauseHeading(`${clauseNum}. Executor and Trustee Powers`));
  children.push(body("My Executors and Trustees shall have the following powers in addition to those conferred by law:"));
  children.push(body("(a) Power to sell, call in and convert into money all or any part of my Estate at such time and in such manner as they think fit, with power to postpone such sale, calling in and conversion for so long as they think fit without being liable for any loss."));
  children.push(body("(b) Power to invest the proceeds of sale and any ready money forming part of my Estate in any investments authorised by law for the investment of trust funds."));
  children.push(body("(c) Power to apply the income or capital of any share held on trust for a minor beneficiary for or towards the maintenance, education or benefit of that beneficiary."));
  children.push(body("(d) Power to appropriate any part of my Estate in or towards satisfaction of any legacy or share without requiring the consent of any beneficiary."));
  children.push(body("(e) Power to insure any property forming part of my Estate against any risk and to pay the premiums out of the income or capital of my Estate."));
  clauseNum++;

  // ── Survivorship ──────────────────────────────────────────────────────────
  children.push(clauseHeading(`${clauseNum}. Survivorship`));
  children.push(body(`Any beneficiary under this Will must survive me by a period of ${survivorshipDays} days in order to benefit under this Will. If any beneficiary fails to survive me by ${survivorshipDays} days, the gift to that beneficiary shall lapse and shall fall into the residue of my Estate to be distributed as if that beneficiary had predeceased me.`));
  clauseNum++;

  // ── Disaster Clause ───────────────────────────────────────────────────────
  children.push(clauseHeading(`${clauseNum}. Disaster Clause`));
  children.push(body(disasterClauseNotes || "In the event that all of my beneficiaries named in this Will predecease me or fail to survive me by the required survivorship period, the residue of my Estate shall pass in accordance with the laws of intestacy applicable in England and Wales at the date of my death."));
  clauseNum++;

  // ── Organ Donation ────────────────────────────────────────────────────────
  children.push(clauseHeading(`${clauseNum}. Organ Donation`));
  children.push(body(organDonation ? organDonationText : "I do not wish to make any specific direction in relation to organ donation."));
  clauseNum++;

  // ── Funeral Wishes ────────────────────────────────────────────────────────
  children.push(clauseHeading(`${clauseNum}. Funeral Wishes`));
  children.push(body(funeralWishes || "I leave the arrangements for my funeral to the discretion of my Executors."));
  clauseNum++;

  // ── General Notes ─────────────────────────────────────────────────────────
  if (generalNotes) {
    children.push(clauseHeading(`${clauseNum}. General Notes`));
    children.push(body(generalNotes));
    clauseNum++;
  }

  // ── Attestation ───────────────────────────────────────────────────────────
  children.push(...buildAttestationBlock(name));

  // ── Footer ────────────────────────────────────────────────────────────────
  children.push(...blank(2));
  children.push(new Paragraph({
    children: [new TextRun({
      text: `Genesis Wills and Estate Planning Ltd  \u2022  ${name}  \u2022  Last Will & Testament${fileRef ? `  \u2022  Ref: ${fileRef}` : ""}`,
      size: COVER_SMALL_SIZE,
      font: FONT,
      color: "666666",
    })],
    alignment: AlignmentType.CENTER,
    spacing: { before: 200, after: 0 },
  }));

  // ── Assemble ──────────────────────────────────────────────────────────────
  const doc = new Document({
    title: `${name} \u2014 Last Will & Testament`,
    creator: "Genesis Wills and Estate Planning Ltd",
    description: "Last Will and Testament",
    styles: { default: { document: { run: { font: FONT, size: BODY_SIZE } } } },
    sections: [{
      properties: {
        page: {
          margin: {
            top: convertInchesToTwip(1.1),
            right: convertInchesToTwip(1.2),
            bottom: convertInchesToTwip(1.1),
            left: convertInchesToTwip(1.2),
          },
        },
      },
      children,
    }],
  });

  return Packer.toBuffer(doc);
}

// ── Fallback: HTML → DOCX (for saved/edited HTML) ────────────────────────────
export async function htmlToDocx(html: string, title: string): Promise<Buffer> {
  const children: Paragraph[] = [];
  const body2 = html
    .replace(/<style[\s\S]*?<\/style>/gi, "")
    .replace(/<head[\s\S]*?<\/head>/gi, "")
    .replace(/<script[\s\S]*?<\/script>/gi, "")
    // Skip the cover div entirely
    .replace(/<div[^>]*class="[^"]*cover[^"]*"[\s\S]*?(?=<div[^>]*class="[^"]*page[^"]*">)/i, "");

  const simplified = body2
    .replace(/<h1[^>]*>([\s\S]*?)<\/h1>/gi, "\n[[H1]]$1[[/H1]]\n")
    .replace(/<h2[^>]*>([\s\S]*?)<\/h2>/gi, "\n[[H2]]$1[[/H2]]\n")
    .replace(/<h3[^>]*>([\s\S]*?)<\/h3>/gi, "\n[[H3]]$1[[/H3]]\n")
    .replace(/<p[^>]*>([\s\S]*?)<\/p>/gi, "\n[[P]]$1[[/P]]\n")
    .replace(/<li[^>]*>([\s\S]*?)<\/li>/gi, "\n[[LI]]$1[[/LI]]\n")
    .replace(/<hr[^>]*\/?>/gi, "\n[[HR]]\n")
    .replace(/<br\s*\/?>/gi, "\n");

  function decodeEntities(s: string): string {
    return s
      .replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">")
      .replace(/&nbsp;/g, " ").replace(/&ldquo;/g, "\u201C").replace(/&rdquo;/g, "\u201D")
      .replace(/&lsquo;/g, "\u2018").replace(/&rsquo;/g, "\u2019")
      .replace(/&mdash;/g, "\u2014").replace(/&ndash;/g, "\u2013")
      .replace(/&#8203;/g, "").replace(/&[a-z]+;/gi, "");
  }
  function stripTags2(s: string): string {
    return decodeEntities(s.replace(/<[^>]+>/g, "").trim());
  }
  function parseInlineRuns(s: string): TextRun[] {
    const runs: TextRun[] = [];
    const re = /<(\/?)(?:strong|b|em|i|u)(?:\s[^>]*)?>|<br\s*\/?>/gi;
    let last = 0; let bold = false; let italic = false;
    let m: RegExpExecArray | null;
    while ((m = re.exec(s)) !== null) {
      if (m.index > last) {
        const t = decodeEntities(s.slice(last, m.index).replace(/<[^>]+>/g, ""));
        if (t) runs.push(new TextRun({ text: t, bold, italics: italic, size: BODY_SIZE, font: FONT }));
      }
      const f = m[0].toLowerCase(); const closing = m[1] === "/";
      if (f === "<br>" || f === "<br/>") runs.push(new TextRun({ text: "\n", size: BODY_SIZE, font: FONT }));
      else if (f.includes("strong") || f.includes("b>")) bold = !closing;
      else if (f.includes("em") || f.includes("i>")) italic = !closing;
      last = m.index + m[0].length;
    }
    if (last < s.length) {
      const t = decodeEntities(s.slice(last).replace(/<[^>]+>/g, ""));
      if (t) runs.push(new TextRun({ text: t, bold, italics: italic, size: BODY_SIZE, font: FONT }));
    }
    return runs.filter(r => {
      // TextRun doesn't expose .text directly; just filter out empty-looking ones by checking if the run was created with empty text
      return true;
    });
  }

  // Title
  children.push(centred(title, 36, true, 0, 240));

  for (const line of simplified.split("\n")) {
    const t = line.trim();
    if (!t) continue;
    const h1 = t.match(/^\[\[H1\]\]([\s\S]*?)\[\[\/H1\]\]$/);
    if (h1) { children.push(centred(stripTags2(h1[1]), 36, true, 200, 120)); continue; }
    const h2 = t.match(/^\[\[H2\]\]([\s\S]*?)\[\[\/H2\]\]$/);
    if (h2) { children.push(clauseHeading(stripTags2(h2[1]))); continue; }
    const h3 = t.match(/^\[\[H3\]\]([\s\S]*?)\[\[\/H3\]\]$/);
    if (h3) { children.push(subHeading(stripTags2(h3[1]))); continue; }
    const p = t.match(/^\[\[P\]\]([\s\S]*?)\[\[\/P\]\]$/);
    if (p) {
      const inner = p[1].trim();
      if (!inner) continue;
      const runs = parseInlineRuns(inner);
      children.push(new Paragraph({ children: runs.length ? runs : [new TextRun({ text: stripTags2(inner), size: BODY_SIZE, font: FONT })], alignment: AlignmentType.JUSTIFIED, spacing: { before: 80, after: 120 } }));
      continue;
    }
    const li = t.match(/^\[\[LI\]\]([\s\S]*?)\[\[\/LI\]\]$/);
    if (li) { children.push(bullet(stripTags2(li[1]))); continue; }
    if (t === "[[HR]]") { children.push(hr()); continue; }
  }

  const doc = new Document({
    title,
    creator: "Genesis Wills and Estate Planning Ltd",
    styles: { default: { document: { run: { font: FONT, size: BODY_SIZE } } } },
    sections: [{
      properties: {
        page: {
          margin: {
            top: convertInchesToTwip(1.1),
            right: convertInchesToTwip(1.2),
            bottom: convertInchesToTwip(1.1),
            left: convertInchesToTwip(1.2),
          },
        },
      },
      children,
    }],
  });
  return Packer.toBuffer(doc);
}
